// data/sectors.js
export const sectors_list = [
    "Agricultura y Agroindustria",
    "Alimentación y Bebidas",
    "Automoción y Transporte",
    "Banca y Servicios Financieros",
    "Bienes de Consumo",
    "Construcción y Materiales",
    "Consultoría y Servicios Profesionales",
    "Defensa y Aeroespacial",
    "Educación y Formación",
    "Energía y Recursos Naturales",
    "Entretenimiento y Medios",
    "Farmacéutica y Biotecnología",
    "Gestión de Residuos y Reciclaje",
    "Industria Química",
    "Ingeniería y Manufactura",
    "Inmobiliario y Propiedades",
    "Logística y Cadena de Suministro",
    "Maquinaria e Industria Pesada",
    "Minería y Metales",
    "Moda y Textil",
    "Petróleo y Gas",
    "Producción y Energías Renovables",
    "Retail y Comercio Minorista",
    "Salud y Servicios Médicos",
    "Seguros",
    "Servicios de Tecnología de la Información",
    "Telecomunicaciones",
    "Turismo y Hotelería",
    "Transporte y Logística",
    "Tecnología y Software",
    "Electrónica y Hardware",
    "Media y Publicidad",
    "Deportes y Recreación",
    "Juegos y Videojuegos",
    "Servicios Ambientales",
    "Servicios Jurídicos y Legales",
    "Asociaciones y Organizaciones Sin Fines de Lucro",
    "Producción Audiovisual y Cinematografía",
    "Ciberseguridad",
    "E-commerce y Marketplaces",
    "Mantenimiento y Limpieza",
    "Muebles y Decoración",
    "Servicios Funerarios y Memoriales",
    "Servicios de Catering y Restauración",
    "Educación Tecnológica y EdTech",
    "Bioplásticos y Materiales Sostenibles",
    "Servicios de Seguridad Física y Electrónica",
    "Cuidado Personal y Cosmética",
    "Servicios de Alquiler y Leasing",
    "Entretenimiento Deportivo y Eventos",
  ];
  